In [ ]:
#import libraries
import pandas as pd
import re
import numpy as np 
import string
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer 
nltk.download('wordnet')
nltk.download('stopwords')
nltk.download('punkt')
import nltk
import re
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import warnings
warnings.filterwarnings('ignore')

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.multiclass import OneVsRestClassifier
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import f1_score,precision_score,confusion_matrix,recall_score,accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import AdaBoostClassifier,GradientBoostingClassifier
from xgboost import XGBClassifier
from nltk.classify import NaiveBayesClassifier
from collections import Counter
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score, confusion_matrix, accuracy_score, classification_report
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from textblob import TextBlob
from textblob.sentiments import NaiveBayesAnalyzer
from textblob.np_extractors import ConllExtractor
from sklearn.feature_extraction.text import CountVectorizer 
from sklearn.pipeline import make_pipeline
from nltk.tokenize import RegexpTokenizer
#warnings.filterwarnings("ignore", category=DeprecationWarning)
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [ ]:
df=pd.read_csv("/content/financial_sentiment_data.csv")

In [ ]:
# Dropping the duplicates

df.drop_duplicates(inplace=True)

In [ ]:
#Text Cleaning
def Text_Cleaning(Text):    
    # Lowercase the texts
    Text = Text.lower()

    # Cleaning punctuations in the text
    punc = str.maketrans(string.punctuation, ' '*len(string.punctuation))
    Text = Text.translate(punc)

    # Removing numbers in the text
    Text = re.sub(r'\d+', '', Text)

    # Removing links
    Text = re.sub('https?://\S+|www\.\S+', '', Text)

    # Deleting newlines
    Text = re.sub('\n', '', Text)

    return Text

#Text Preprocessing
# Stopwords
Stopwords = set(nltk.corpus.stopwords.words("english")) - set(["not"])

def Text_Processing(Text):    
    Processed_Text = list()
    Lemmatizer = WordNetLemmatizer()

    # Tokens of Words
    Tokens = nltk.word_tokenize(Text)

    # Removing Stopwords and Lemmatizing Words

    for word in Tokens:
        if word not in Stopwords:            
            Processed_Text.append(Lemmatizer.lemmatize(word))            
    return(" ".join(Processed_Text))

In [ ]:
#Apply the functions
df['Sentence'] = df['Sentence'].apply(Text_Cleaning).apply(Text_Processing)

In [ ]:
df

Sentence Sentiment
0     geosolutions technology leverage benefon gps s...  positive
1                           esi low bk real possibility  negative
2     last quarter componenta net sale doubled eurm ...  positive
3     according finnish russian chamber commerce maj...   neutral
4     swedish buyout firm sold remaining percent sta...   neutral
...                                                 ...       ...
5837  rising cost forced packaging producer huhtamak...  negative
5838  nordic walking first used summer training meth...   neutral
5839  according shipping company viking line eu deci...   neutral
5840  building home improvement trade sale decreased...   neutral
5841  helsinki afx kci konecranes said order four ho...  positive

[5836 rows x 2 columns]

In [ ]:
positive_words=[]
negative_words=[]
neutral_words=[]

In [ ]:
for index,column in df.iterrows():
    text=column['Sentence']
    sentiment=column['Sentiment']
    words=word_tokenize(text)
    if sentiment=='positive':
        positive_words.extend(words)
    elif sentiment=='negative':
        negative_words.extend(words)
    else:
        neutral_words.extend(words)
        

In [ ]:
positive_words=set(positive_words)
negative_words=set(negative_words)
neutral_words=set(neutral_words)

In [ ]:
positive_words

{'legal',
 'vr',
 'uoefjlop',
 'vesa',
 'interbank',
 'tripled',
 'sell',
 'faculty',
 'fda',
 'nortel',
 'marketresearch',
 'qnx',
 'talktalk',
 'north',
 '¬maco',
 'emerging',
 'exact',
 'residentialconstruction',
 'medically',
 'contributed',
 'structure',
 'orhangazi',
 'grew',
 'pct',
 'challendge',
 'volvo',
 'pearl',
 'accumulation',
 'exel',
 'biggest',
 'norilsk',
 'ii',
 'alliance',
 'megaas',
 'win',
 'crk',
 'abn',
 'structural',
 'professional',
 'tailored',
 'dedm',
 'slide',
 'mouth',
 'longs',
 'bib',
 'block',
 'triple',
 'poor',
 'shift',
 'blackstone',
 'mirabela',
 'siriusxm',
 'slid',
 'projected',
 'lkab',
 'metric',
 'hr',
 'mmov',
 'entreprenor',
 'oct',
 'play',
 'approves',
 'wynn',
 'unless',
 'etteplan',
 'well',
 'concern',
 'exceeded',
 'ntt',
 'river',
 'seen',
 'expiration',
 'thanksto',
 'near',
 'name',
 'fgvoip',
 'receive',
 'promise',
 'kjzuzmu',
 'distinguished',
 'swoope',
 'investor',
 'custody',
 'thus',
 'plaza',
 'gold',
 'holiday',
 'tally',


In [ ]:
negative_words

{'legal',
 'sell',
 'fda',
 'talktalk',
 'north',
 'emerging',
 'tail',
 'bothnia',
 'pct',
 'soullor',
 'exel',
 'jrmw',
 'survey',
 'biggest',
 'alliance',
 'win',
 'slide',
 'brewing',
 'longs',
 'poor',
 'shift',
 'forced',
 'explain',
 'valio',
 'communicated',
 'slid',
 'engagement',
 'play',
 'unless',
 'wynn',
 'oct',
 'lember',
 'trailer',
 'cree',
 'well',
 'subsequent',
 'concern',
 'seen',
 'near',
 'promise',
 'investor',
 'booking',
 'drillisch',
 'dailystockplays',
 'grappling',
 'pwc',
 'seawind',
 'reduced',
 'recall',
 'net',
 'diageo',
 'icy',
 'hasten',
 'asthma',
 'noted',
 'ebit',
 'macd',
 'careful',
 'scfv',
 'main',
 'okmetic',
 'meat',
 'combination',
 'change',
 'director',
 'rim',
 'level',
 'credit',
 'watchlist',
 'bread',
 'distributable',
 'signal',
 'rejected',
 'effective',
 'trg',
 'plunge',
 'representative',
 'tonne',
 'increasingly',
 'gap',
 'violated',
 'baltic',
 'providing',
 'northern',
 'price',
 'completed',
 'reargument',
 'downgrade',
 'po

In [ ]:
neutral_words

{'legacy',
 'sell',
 'skogster',
 'north',
 'grew',
 'evraz',
 'multiplayer',
 'logical',
 'mustonen',
 'survey',
 'whitehall',
 'alliance',
 'corroborate',
 'abn',
 'bib',
 'fabrication',
 'kalinisky',
 'heavily',
 'valkama',
 'ruwais',
 'footwear',
 'yield',
 'investor',
 'interior',
 'image',
 'kontturi',
 'tent',
 'arranged',
 'bangkok',
 'logset',
 'harold',
 'undertaken',
 'dvd',
 'panama',
 'moisture',
 'maritim',
 'voting',
 'scfv',
 'fulfilment',
 'rim',
 'credit',
 'ca',
 'crucially',
 'effective',
 'magnet',
 'tonne',
 'helisnki',
 'autonomous',
 'paul',
 'price',
 'resolve',
 'maintains',
 'calif',
 'lennon',
 'saying',
 'pekkarinen',
 'bioview',
 'say',
 'junction',
 'specie',
 'judgement',
 'mti',
 'ensure',
 'conduct',
 'discussion',
 'rug',
 'randgold',
 'airtel',
 'globe',
 'raiffeisen',
 'workout',
 'flow',
 'vega',
 'raute',
 'synergy',
 'local',
 'ta',
 'marked',
 'jukka',
 'bullish',
 'wwd',
 'user',
 'irrevocable',
 'pharmacokinetics',
 'resurrect',
 'ab',
 'basem

In [ ]:
common_words= set(positive_words).intersection(negative_words,neutral_words)
common_words

{'legal',
 'sell',
 'north',
 'emerging',
 'pct',
 'exel',
 'biggest',
 'alliance',
 'win',
 'slide',
 'poor',
 'shift',
 'slid',
 'oct',
 'play',
 'unless',
 'well',
 'concern',
 'seen',
 'near',
 'promise',
 'investor',
 'reduced',
 'recall',
 'net',
 'noted',
 'asthma',
 'ebit',
 'main',
 'okmetic',
 'meat',
 'combination',
 'change',
 'director',
 'level',
 'credit',
 'effective',
 'signal',
 'rejected',
 'representative',
 'tonne',
 'gap',
 'baltic',
 'providing',
 'northern',
 'price',
 'completed',
 'pound',
 'single',
 'saying',
 'following',
 'say',
 'bull',
 'ing',
 'tech',
 'remain',
 'executive',
 'quite',
 'flow',
 'result',
 'raute',
 'local',
 'ta',
 'brazil',
 'bullish',
 'large',
 'insurer',
 'user',
 'ab',
 'award',
 'alma',
 'normal',
 'available',
 'broker',
 'matter',
 'strategy',
 'corporation',
 'rapid',
 'resulted',
 'although',
 'almost',
 'slow',
 'productional',
 'financing',
 'refining',
 'atrium',
 'fiscal',
 'resort',
 'sto',
 'buyer',
 'increased',
 'carg

In [ ]:
unique_words=positive_words.union(negative_words,neutral_words)-common_words
unique_words

{'legacy',
 '¬maco',
 'skogster',
 'residentialconstruction',
 'exact',
 'grew',
 'evraz',
 'tail',
 'multiplayer',
 'logical',
 'mustonen',
 'survey',
 'whitehall',
 'corroborate',
 'abn',
 'dedm',
 'bib',
 'fabrication',
 'blackstone',
 'kalinisky',
 'heavily',
 'valkama',
 'cree',
 'ruwais',
 'exceeded',
 'thanksto',
 'footwear',
 'yield',
 'interior',
 'image',
 'kontturi',
 'tent',
 'arranged',
 'bangkok',
 'logset',
 'harold',
 'undertaken',
 'establishing',
 'dvd',
 'panama',
 'moisture',
 'maritim',
 'suburb',
 'vahhjacbfg',
 'voting',
 'careful',
 'scfv',
 'fulfilment',
 'primark',
 'rim',
 'steam',
 'watchlist',
 'ca',
 'crucially',
 'scty',
 'dj',
 'magnet',
 'plunge',
 'abov',
 'helisnki',
 'autonomous',
 'paul',
 'chartology',
 'downgrade',
 'resolve',
 'maintains',
 'calif',
 'lennon',
 'pekkarinen',
 'showing',
 'bioview',
 'adsk',
 'xfn',
 'junction',
 'judgement',
 'specie',
 'ingerois',
 'mti',
 'ensure',
 'conduct',
 'discussion',
 'vtppzyuy',
 'rug',
 'randgold',
 '

In [ ]:
positive_unique_words=(positive_words-common_words)
positive_unique_words

{'vr',
 'uoefjlop',
 'vesa',
 'interbank',
 'tripled',
 'faculty',
 '¬maco',
 'fda',
 'nortel',
 'marketresearch',
 'qnx',
 'talktalk',
 'residentialconstruction',
 'medically',
 'exact',
 'contributed',
 'orhangazi',
 'structure',
 'grew',
 'challendge',
 'volvo',
 'pearl',
 'accumulation',
 'norilsk',
 'ii',
 'megaas',
 'crk',
 'abn',
 'structural',
 'professional',
 'dedm',
 'mouth',
 'longs',
 'bib',
 'block',
 'triple',
 'blackstone',
 'mirabela',
 'siriusxm',
 'projected',
 'lkab',
 'metric',
 'hr',
 'mmov',
 'entreprenor',
 'wynn',
 'approves',
 'etteplan',
 'exceeded',
 'ntt',
 'river',
 'expiration',
 'thanksto',
 'name',
 'fgvoip',
 'receive',
 'kjzuzmu',
 'distinguished',
 'swoope',
 'custody',
 'thus',
 'plaza',
 'gold',
 'tally',
 'bullya',
 'electriccar',
 'push',
 'tco',
 'invoice',
 'dailystockplays',
 'recommendation',
 'pouring',
 'fi',
 'establishing',
 'auto',
 'immediate',
 'anheuser',
 'honkamaa',
 'diageo',
 'vertex',
 'macd',
 'suburb',
 'vahhjacbfg',
 'observes

In [ ]:
negative_unique_words=negative_words-common_words
negative_unique_words

{'dive',
 'suspends',
 'stalwart',
 'retreat',
 'arokarhu',
 'roiled',
 'petrofac',
 'slope',
 'hard',
 'cinema',
 'xcngwstq',
 'boycotting',
 'seikku',
 'blrx',
 'emc',
 'rsi',
 'scala',
 'mpwr',
 'overhead',
 'pressed',
 'icy',
 'inspection',
 'wynn',
 'cree',
 'uup',
 'foul',
 'probe',
 'emsa',
 'scaling',
 'meggitt',
 'altogether',
 'wrong',
 'profile',
 'rig',
 'fallen',
 'determining',
 'military',
 'qcom',
 'sterv',
 'bno',
 'dji',
 '¼',
 'slowed',
 'jury',
 'fio',
 'nkwecrba',
 'laboratory',
 'underperform',
 'saltonstall',
 'seasonal',
 'pushed',
 'bodily',
 'footing',
 'toxic',
 'rkkm',
 'iwm',
 'pride',
 'runup',
 'lodged',
 'fmcn',
 'vxtamnpk',
 'empty',
 'scfv',
 'gmt',
 'dish',
 'rim',
 'skf',
 'csco',
 'agree',
 'andy',
 'newsroom',
 'banned',
 'calling',
 'affectogenimap',
 'employment',
 'ebay',
 'duration',
 'cisco',
 'routine',
 'lag',
 'lguybxeze',
 'stifel',
 'bat',
 'administrative',
 'payment',
 'painful',
 'taloustutkimus',
 'soda',
 'slv',
 'generally',
 'mortg

In [ ]:
neutral_unique_words=neutral_words-common_words
neutral_unique_words

{'saarijarvi',
 'endustri',
 'late',
 'osmo',
 'fortune',
 'midwest',
 'fantuzzi',
 'completion',
 'toolonlahti',
 'raffle',
 'lifted',
 'dalborg',
 'krona',
 'enefit',
 'arokarhu',
 'battery',
 'whereby',
 'wellness',
 'trojan',
 'village',
 'petrofac',
 'rinkuskiai',
 'styled',
 'telgua',
 'topical',
 'reftele',
 'receptacle',
 'oka',
 'brewer',
 'boycotting',
 'gantry',
 'miniature',
 'umo',
 'shenzhen',
 'finger',
 'castell',
 'strategically',
 'direct',
 'exported',
 'tex',
 'synonymous',
 'live',
 'manchester',
 'inspection',
 'category',
 'gama',
 'flexibly',
 'platen',
 'enclosed',
 'workflow',
 'roman',
 'hevea',
 'leningrad',
 'paycheck',
 'emsa',
 'innovationsmanagement',
 'meggitt',
 'henrik',
 'quantity',
 'driver',
 'environment',
 'alfa',
 'gw',
 'demonstration',
 'profile',
 'choose',
 'luceplan',
 'allow',
 'volunteer',
 'eqt',
 'countervalue',
 'fallen',
 'turmoil',
 'owing',
 'determining',
 'unlike',
 'rib',
 'plywood',
 'qprv',
 'genvec',
 'dovre',
 'slowed',
 'ris

In [ ]:
from nltk import ngrams
tokenized_words=set(positive_unique_words)
positive_unigrams=(list(ngrams(tokenized_words,1)))
positive_bigrams=(list(ngrams(tokenized_words,2)))
positive_trigrams=(list(ngrams(tokenized_words,3)))

In [ ]:
positive_unigrams

[('imperial',),
 ('companiesfresnillo',),
 ('creep',),
 ('late',),
 ('raivv',),
 ('do',),
 ('conglomerate',),
 ('negotiate',),
 ('lifted',),
 ('sustainable',),
 ('zoo',),
 ('trustee',),
 ('whereby',),
 ('tmtanalyst',),
 ('village',),
 ('rinkuskiai',),
 ('brcm',),
 ('obj',),
 ('hillier',),
 ('rost',),
 ('allstarcharts',),
 ('mettler',),
 ('expanding',),
 ('brokerage',),
 ('canada',),
 ('battle',),
 ('master',),
 ('brewer',),
 ('doering',),
 ('gantry',),
 ('shenzhen',),
 ('rsi',),
 ('balfour',),
 ('finger',),
 ('possibly',),
 ('convincing',),
 ('direct',),
 ('kaunas',),
 ('tuition',),
 ('eastern',),
 ('candlestick',),
 ('manchester',),
 ('unique',),
 ('sokonet',),
 ('wynn',),
 ('gyrating',),
 ('ucb',),
 ('category',),
 ('base',),
 ('eyeing',),
 ('mtd',),
 ('connection',),
 ('roaring',),
 ('basing',),
 ('uup',),
 ('interbank',),
 ('jnbcvdcu',),
 ('runner',),
 ('wrote',),
 ('bph',),
 ('mineral',),
 ('leningrad',),
 ('sure',),
 ('roadshow',),
 ('scaling',),
 ('satlan',),
 ('viewpoint',),
 (

In [ ]:
positive_bigrams

[('imperial', 'companiesfresnillo'),
 ('companiesfresnillo', 'creep'),
 ('creep', 'late'),
 ('late', 'raivv'),
 ('raivv', 'do'),
 ('do', 'conglomerate'),
 ('conglomerate', 'negotiate'),
 ('negotiate', 'lifted'),
 ('lifted', 'sustainable'),
 ('sustainable', 'zoo'),
 ('zoo', 'trustee'),
 ('trustee', 'whereby'),
 ('whereby', 'tmtanalyst'),
 ('tmtanalyst', 'village'),
 ('village', 'rinkuskiai'),
 ('rinkuskiai', 'brcm'),
 ('brcm', 'obj'),
 ('obj', 'hillier'),
 ('hillier', 'rost'),
 ('rost', 'allstarcharts'),
 ('allstarcharts', 'mettler'),
 ('mettler', 'expanding'),
 ('expanding', 'brokerage'),
 ('brokerage', 'canada'),
 ('canada', 'battle'),
 ('battle', 'master'),
 ('master', 'brewer'),
 ('brewer', 'doering'),
 ('doering', 'gantry'),
 ('gantry', 'shenzhen'),
 ('shenzhen', 'rsi'),
 ('rsi', 'balfour'),
 ('balfour', 'finger'),
 ('finger', 'possibly'),
 ('possibly', 'convincing'),
 ('convincing', 'direct'),
 ('direct', 'kaunas'),
 ('kaunas', 'tuition'),
 ('tuition', 'eastern'),
 ('eastern', 'ca

In [ ]:
positive_trigrams

[('imperial', 'companiesfresnillo', 'creep'),
 ('companiesfresnillo', 'creep', 'late'),
 ('creep', 'late', 'raivv'),
 ('late', 'raivv', 'do'),
 ('raivv', 'do', 'conglomerate'),
 ('do', 'conglomerate', 'negotiate'),
 ('conglomerate', 'negotiate', 'lifted'),
 ('negotiate', 'lifted', 'sustainable'),
 ('lifted', 'sustainable', 'zoo'),
 ('sustainable', 'zoo', 'trustee'),
 ('zoo', 'trustee', 'whereby'),
 ('trustee', 'whereby', 'tmtanalyst'),
 ('whereby', 'tmtanalyst', 'village'),
 ('tmtanalyst', 'village', 'rinkuskiai'),
 ('village', 'rinkuskiai', 'brcm'),
 ('rinkuskiai', 'brcm', 'obj'),
 ('brcm', 'obj', 'hillier'),
 ('obj', 'hillier', 'rost'),
 ('hillier', 'rost', 'allstarcharts'),
 ('rost', 'allstarcharts', 'mettler'),
 ('allstarcharts', 'mettler', 'expanding'),
 ('mettler', 'expanding', 'brokerage'),
 ('expanding', 'brokerage', 'canada'),
 ('brokerage', 'canada', 'battle'),
 ('canada', 'battle', 'master'),
 ('battle', 'master', 'brewer'),
 ('master', 'brewer', 'doering'),
 ('brewer', 'doe

In [ ]:
tokenized_words=set(negative_unique_words)
negative_unigrams=(list(ngrams(tokenized_words,1)))
negative_bigrams=(list(ngrams(tokenized_words,2)))
negative_trigrams=(list(ngrams(tokenized_words,3)))
negative_unigrams

[('hhhmm',),
 ('dive',),
 ('intertek',),
 ('excess',),
 ('teaexxpe',),
 ('resume',),
 ('suspends',),
 ('stalwart',),
 ('nke',),
 ('rio',),
 ('retreat',),
 ('arokarhu',),
 ('roiled',),
 ('dropped',),
 ('petrofac',),
 ('kesbv',),
 ('thicker',),
 ('slope',),
 ('ease',),
 ('aaland',),
 ('hard',),
 ('fastenal',),
 ('running',),
 ('trendline',),
 ('cinema',),
 ('xcngwstq',),
 ('boycotting',),
 ('seikku',),
 ('blrx',),
 ('publishing',),
 ('cqkr',),
 ('soullor',),
 ('delayed',),
 ('emc',),
 ('kraft',),
 ('rsi',),
 ('vwap',),
 ('kronor',),
 ('scala',),
 ('mpwr',),
 ('overhead',),
 ('pressed',),
 ('icy',),
 ('inspection',),
 ('wynn',),
 ('dia',),
 ('cree',),
 ('uup',),
 ('scanfil',),
 ('weakness',),
 ('casino',),
 ('slash',),
 ('fxe',),
 ('foul',),
 ('probe',),
 ('emsa',),
 ('hacking',),
 ('scaling',),
 ('meggitt',),
 ('pile',),
 ('stx',),
 ('altogether',),
 ('wrong',),
 ('profile',),
 ('worst',),
 ('mount',),
 ('rig',),
 ('upmv',),
 ('fined',),
 ('fallen',),
 ('determining',),
 ('jp',),
 ('divi

In [ ]:
negative_bigrams

[('hhhmm', 'dive'),
 ('dive', 'intertek'),
 ('intertek', 'excess'),
 ('excess', 'teaexxpe'),
 ('teaexxpe', 'resume'),
 ('resume', 'suspends'),
 ('suspends', 'stalwart'),
 ('stalwart', 'nke'),
 ('nke', 'rio'),
 ('rio', 'retreat'),
 ('retreat', 'arokarhu'),
 ('arokarhu', 'roiled'),
 ('roiled', 'dropped'),
 ('dropped', 'petrofac'),
 ('petrofac', 'kesbv'),
 ('kesbv', 'thicker'),
 ('thicker', 'slope'),
 ('slope', 'ease'),
 ('ease', 'aaland'),
 ('aaland', 'hard'),
 ('hard', 'fastenal'),
 ('fastenal', 'running'),
 ('running', 'trendline'),
 ('trendline', 'cinema'),
 ('cinema', 'xcngwstq'),
 ('xcngwstq', 'boycotting'),
 ('boycotting', 'seikku'),
 ('seikku', 'blrx'),
 ('blrx', 'publishing'),
 ('publishing', 'cqkr'),
 ('cqkr', 'soullor'),
 ('soullor', 'delayed'),
 ('delayed', 'emc'),
 ('emc', 'kraft'),
 ('kraft', 'rsi'),
 ('rsi', 'vwap'),
 ('vwap', 'kronor'),
 ('kronor', 'scala'),
 ('scala', 'mpwr'),
 ('mpwr', 'overhead'),
 ('overhead', 'pressed'),
 ('pressed', 'icy'),
 ('icy', 'inspection'),
 (

In [ ]:
negative_trigrams

[('hhhmm', 'dive', 'intertek'),
 ('dive', 'intertek', 'excess'),
 ('intertek', 'excess', 'teaexxpe'),
 ('excess', 'teaexxpe', 'resume'),
 ('teaexxpe', 'resume', 'suspends'),
 ('resume', 'suspends', 'stalwart'),
 ('suspends', 'stalwart', 'nke'),
 ('stalwart', 'nke', 'rio'),
 ('nke', 'rio', 'retreat'),
 ('rio', 'retreat', 'arokarhu'),
 ('retreat', 'arokarhu', 'roiled'),
 ('arokarhu', 'roiled', 'dropped'),
 ('roiled', 'dropped', 'petrofac'),
 ('dropped', 'petrofac', 'kesbv'),
 ('petrofac', 'kesbv', 'thicker'),
 ('kesbv', 'thicker', 'slope'),
 ('thicker', 'slope', 'ease'),
 ('slope', 'ease', 'aaland'),
 ('ease', 'aaland', 'hard'),
 ('aaland', 'hard', 'fastenal'),
 ('hard', 'fastenal', 'running'),
 ('fastenal', 'running', 'trendline'),
 ('running', 'trendline', 'cinema'),
 ('trendline', 'cinema', 'xcngwstq'),
 ('cinema', 'xcngwstq', 'boycotting'),
 ('xcngwstq', 'boycotting', 'seikku'),
 ('boycotting', 'seikku', 'blrx'),
 ('seikku', 'blrx', 'publishing'),
 ('blrx', 'publishing', 'cqkr'),
 ('

In [ ]:
tokenized_words=set(neutral_unique_words)
neutral_unigrams=(list(ngrams(tokenized_words,1)))
neutral_bigrams=(list(ngrams(tokenized_words,2)))
neutral_trigrams=(list(ngrams(tokenized_words,3)))
neutral_unigrams

[('saarijarvi',),
 ('endustri',),
 ('late',),
 ('osmo',),
 ('fortune',),
 ('midwest',),
 ('fantuzzi',),
 ('completion',),
 ('toolonlahti',),
 ('raffle',),
 ('lifted',),
 ('dalborg',),
 ('krona',),
 ('enefit',),
 ('arokarhu',),
 ('battery',),
 ('whereby',),
 ('wellness',),
 ('trojan',),
 ('village',),
 ('petrofac',),
 ('rinkuskiai',),
 ('styled',),
 ('telgua',),
 ('topical',),
 ('reftele',),
 ('receptacle',),
 ('oka',),
 ('brewer',),
 ('boycotting',),
 ('gantry',),
 ('miniature',),
 ('umo',),
 ('shenzhen',),
 ('finger',),
 ('castell',),
 ('strategically',),
 ('direct',),
 ('exported',),
 ('tex',),
 ('synonymous',),
 ('live',),
 ('manchester',),
 ('inspection',),
 ('category',),
 ('gama',),
 ('flexibly',),
 ('platen',),
 ('enclosed',),
 ('workflow',),
 ('roman',),
 ('hevea',),
 ('leningrad',),
 ('paycheck',),
 ('emsa',),
 ('innovationsmanagement',),
 ('meggitt',),
 ('henrik',),
 ('quantity',),
 ('driver',),
 ('environment',),
 ('alfa',),
 ('gw',),
 ('demonstration',),
 ('profile',),
 ('c

In [ ]:
neutral_bigrams

[('saarijarvi', 'endustri'),
 ('endustri', 'late'),
 ('late', 'osmo'),
 ('osmo', 'fortune'),
 ('fortune', 'midwest'),
 ('midwest', 'fantuzzi'),
 ('fantuzzi', 'completion'),
 ('completion', 'toolonlahti'),
 ('toolonlahti', 'raffle'),
 ('raffle', 'lifted'),
 ('lifted', 'dalborg'),
 ('dalborg', 'krona'),
 ('krona', 'enefit'),
 ('enefit', 'arokarhu'),
 ('arokarhu', 'battery'),
 ('battery', 'whereby'),
 ('whereby', 'wellness'),
 ('wellness', 'trojan'),
 ('trojan', 'village'),
 ('village', 'petrofac'),
 ('petrofac', 'rinkuskiai'),
 ('rinkuskiai', 'styled'),
 ('styled', 'telgua'),
 ('telgua', 'topical'),
 ('topical', 'reftele'),
 ('reftele', 'receptacle'),
 ('receptacle', 'oka'),
 ('oka', 'brewer'),
 ('brewer', 'boycotting'),
 ('boycotting', 'gantry'),
 ('gantry', 'miniature'),
 ('miniature', 'umo'),
 ('umo', 'shenzhen'),
 ('shenzhen', 'finger'),
 ('finger', 'castell'),
 ('castell', 'strategically'),
 ('strategically', 'direct'),
 ('direct', 'exported'),
 ('exported', 'tex'),
 ('tex', 'synony

In [ ]:
neutral_trigrams

[('saarijarvi', 'endustri', 'late'),
 ('endustri', 'late', 'osmo'),
 ('late', 'osmo', 'fortune'),
 ('osmo', 'fortune', 'midwest'),
 ('fortune', 'midwest', 'fantuzzi'),
 ('midwest', 'fantuzzi', 'completion'),
 ('fantuzzi', 'completion', 'toolonlahti'),
 ('completion', 'toolonlahti', 'raffle'),
 ('toolonlahti', 'raffle', 'lifted'),
 ('raffle', 'lifted', 'dalborg'),
 ('lifted', 'dalborg', 'krona'),
 ('dalborg', 'krona', 'enefit'),
 ('krona', 'enefit', 'arokarhu'),
 ('enefit', 'arokarhu', 'battery'),
 ('arokarhu', 'battery', 'whereby'),
 ('battery', 'whereby', 'wellness'),
 ('whereby', 'wellness', 'trojan'),
 ('wellness', 'trojan', 'village'),
 ('trojan', 'village', 'petrofac'),
 ('village', 'petrofac', 'rinkuskiai'),
 ('petrofac', 'rinkuskiai', 'styled'),
 ('rinkuskiai', 'styled', 'telgua'),
 ('styled', 'telgua', 'topical'),
 ('telgua', 'topical', 'reftele'),
 ('topical', 'reftele', 'receptacle'),
 ('reftele', 'receptacle', 'oka'),
 ('receptacle', 'oka', 'brewer'),
 ('oka', 'brewer', 'boy

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB


In [ ]:
# Load the dataset
#df = pd.read_csv('path/to/dataset.csv')
from sklearn.feature_extraction.text import TfidfVectorizer
# Extract the top 500 unique positive, negative, and neutral words
vectorizer = TfidfVectorizer(max_features=500, stop_words='english')
X = vectorizer.fit_transform(df['Sentence'])
y = df['Sentiment']
features = vectorizer.vocabulary_.keys()
freq = X.sum(axis=0).A1
word_freq = dict(zip(features, freq))
sorted_words = sorted(word_freq.items(), key=lambda x: x[1], reverse=True)
top_positive_words = [word[0] for word in sorted_words if word[0] not in ['negative', 'neutral'] and word[1] > 0][:500]
top_negative_words = [word[0] for word in sorted_words if word[0] not in ['positive', 'neutral'] and word[1] > 0][:500]
top_neutral_words = [word[0] for word in sorted_words if word[0] not in ['positive', 'negative'] and word[1] > 0][:500]

In [ ]:
len(top_positive_words)

499

In [ ]:
top_positive_words

['eps',
 'industrial',
 'option',
 'place',
 'daily',
 'material',
 'standard',
 'november',
 'scheduled',
 'strong',
 'volume',
 'measure',
 'fixed',
 'chief',
 'london',
 'meeting',
 'employee',
 'acquisition',
 'manufacture',
 'device',
 'outlook',
 'nordea',
 'posted',
 'cash',
 'sanoma',
 'right',
 'fund',
 'making',
 'product',
 'alma',
 'production',
 'test',
 'pretax',
 'flow',
 'europe',
 'decreased',
 'water',
 'month',
 'approximately',
 'expected',
 'cut',
 'income',
 'technology',
 'oyj',
 'market',
 'yesterday',
 'purchase',
 'today',
 'position',
 'board',
 'remain',
 'mr',
 'support',
 'based',
 'excluding',
 'plc',
 'venture',
 'estimate',
 'company',
 'close',
 'end',
 'european',
 'project',
 'credit',
 'oil',
 'office',
 'january',
 'way',
 'issued',
 'versus',
 'april',
 'development',
 'sale',
 'time',
 'communication',
 'executive',
 'staff',
 'added',
 'october',
 'elcoteq',
 'agreement',
 'worth',
 'nokia',
 'bn',
 'capman',
 'industry',
 'corp',
 'application'

In [ ]:

# Create a new dataframe with the top 200 positive, negative, and neutral words as features
new_df = pd.DataFrame()
for word in top_positive_words + top_negative_words + top_neutral_words:
    new_df[word] = df['Sentence'].apply(lambda x: 1 if word in x else 0)
new_df['Sentiment'] = df['Sentiment']

In [ ]:
new_df

eps  industrial  option  place  daily  material  standard  november  \
0       0           0       0      0      0         0         0         0   
1       0           0       0      0      0         0         0         0   
2       0           0       0      0      0         0         0         0   
3       0           0       0      0      0         0         0         0   
4       0           0       0      0      0         0         0         0   
...   ...         ...     ...    ...    ...       ...       ...       ...   
5837    0           0       0      0      0         0         0         0   
5838    0           0       0      0      0         0         0         0   
5839    0           0       0      0      0         0         0         0   
5840    0           0       0      0      0         0         0         0   
5841    0           0       0      0      0         0         0         0   

      scheduled  strong  ...  half  helsinki  main  manufacturing  quarter  \
0             0       0  ...     0         0     0              0        0   
1             0       0  ...     0         0     0              0        0   
2             0       0  ...     0         0     0              0        1   
3             0       0  ...     0         0     0              0        0   
4             0       0  ...     0         0     1              0        0   
...         ...     ...  ...   ...       ...   ...            ...      ...   
5837          0       0  ...     0         0     0              1        0   
5838          0       0  ...     0         0     0              0        0   
5839          0       0  ...     0         0     0              0        0   
5840          0       0  ...     0         0     0              0        0   
5841          0       0  ...     0         1     0              0        0   

      member  fb  sell  negative  Sentiment  
0          0   0     0         0   positive  
1          0   0     0         0   negative  
2          0   0     0         0   positive  
3          0   0     0         0    neutral  
4          0   0     0         0    neutral  
...      ...  ..   ...       ...        ...  
5837       0   0     0         0   negative  
5838       0   0     0         0    neutral  
5839       0   0     0         0    neutral  
5840       0   0     0         0    neutral  
5841       0   0     0         0   positive  

[5836 rows x 501 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder
le_encoder = LabelEncoder()
new_df["Labels"] = le_encoder.fit_transform(new_df["Sentiment"])
new_df

eps  industrial  option  place  daily  material  standard  november  \
0       0           0       0      0      0         0         0         0   
1       0           0       0      0      0         0         0         0   
2       0           0       0      0      0         0         0         0   
3       0           0       0      0      0         0         0         0   
4       0           0       0      0      0         0         0         0   
...   ...         ...     ...    ...    ...       ...       ...       ...   
5837    0           0       0      0      0         0         0         0   
5838    0           0       0      0      0         0         0         0   
5839    0           0       0      0      0         0         0         0   
5840    0           0       0      0      0         0         0         0   
5841    0           0       0      0      0         0         0         0   

      scheduled  strong  ...  helsinki  main  manufacturing  quarter  member  \
0             0       0  ...         0     0              0        0       0   
1             0       0  ...         0     0              0        0       0   
2             0       0  ...         0     0              0        1       0   
3             0       0  ...         0     0              0        0       0   
4             0       0  ...         0     1              0        0       0   
...         ...     ...  ...       ...   ...            ...      ...     ...   
5837          0       0  ...         0     0              1        0       0   
5838          0       0  ...         0     0              0        0       0   
5839          0       0  ...         0     0              0        0       0   
5840          0       0  ...         0     0              0        0       0   
5841          0       0  ...         1     0              0        0       0   

      fb  sell  negative  Sentiment  Labels  
0      0     0         0   positive       2  
1      0     0         0   negative       0  
2      0     0         0   positive       2  
3      0     0         0    neutral       1  
4      0     0         0    neutral       1  
...   ..   ...       ...        ...     ...  
5837   0     0         0   negative       0  
5838   0     0         0    neutral       1  
5839   0     0         0    neutral       1  
5840   0     0         0    neutral       1  
5841   0     0         0   positive       2  

[5836 rows x 502 columns]

In [ ]:

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(new_df.drop(['Sentiment','Labels'], axis=1), new_df['Labels'], test_size=0.2)

# Train a Naive Bayes classifier on the training set
clf = MultinomialNB()
clf.fit(X_train, y_train)

# Test the model on the testing set and print the accuracy score
accuracy = clf.score(X_test, y_test)
print('Accuracy:', accuracy)


Accuracy: 0.6558219178082192


In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
clf = LogisticRegression()
clf.fit(X_train, y_train)

# Test the model on the testing set and print the accuracy score
accuracy = clf.score(X_test, y_test)
print('Accuracy:', accuracy)

Accuracy: 0.6686643835616438


In [ ]:
# Train an XGBoost model on the training set
dtrain = xgb.DMatrix(X_train, label=y_train)
dtest = xgb.DMatrix(X_test, label=y_test)

param = {
    'max_depth': 6,
    'eta': 0.3,
    'objective': 'multi:softmax',
    'num_class': 3
}

num_round = 100
model = xgb.train(param, dtrain, num_round)

# Test the model on the testing set and print the accuracy score
preds = model.predict(dtest)
accuracy = sum(preds == y_test) / len(y_test)
print('Accuracy:', accuracy)

Accuracy: 0.6575342465753424


In [ ]:
# Load the dataset
#df = pd.read_csv('path/to/dataset.csv')
from sklearn.feature_extraction.text import TfidfVectorizer
# Extract the top 200 unique positive, negative, and neutral words
vectorizer = TfidfVectorizer(max_features=500, stop_words='english',ngram_range=(2, 2))
X = vectorizer.fit_transform(df['Sentence'])
y = df['Sentiment']
features = vectorizer.vocabulary_.keys()
freq = X.sum(axis=0).A1
word_freq = dict(zip(features, freq))
sorted_words = sorted(word_freq.items(), key=lambda x: x[1], reverse=True)
top_positive_words_bigram = [word[0] for word in sorted_words if word[0] not in ['negative', 'neutral'] and word[1] > 0][:500]
top_negative_words_bigram = [word[0] for word in sorted_words if word[0] not in ['positive', 'neutral'] and word[1] > 0][:500]
top_neutral_words_bigram = [word[0] for word in sorted_words if word[0] not in ['positive', 'negative'] and word[1] > 0][:500]

In [ ]:
len(top_negative_words_bigram)

500

In [ ]:
top_negative_words_bigram

['profit fell',
 'outside finland',
 'sector player',
 'eur corresponding',
 'based company',
 'chairman board',
 'share eur',
 'earnings share',
 'global research',
 'eur billion',
 'componenta oyj',
 'maker rautaruukki',
 'ilkka yhtyma',
 'suominen corporation',
 'eur usd',
 'united state',
 'new york',
 'month mln',
 'company operating',
 'royal mail',
 'sale decreased',
 'pharmaceutical market',
 'life science',
 'employ approximately',
 'million usd',
 'quarter year',
 'helsinki afx',
 'profit euro',
 'employee company',
 'finnish scanfil',
 'manufacturer scanfil',
 'food industry',
 'fixed network',
 'silicon wafer',
 'danske bank',
 'product development',
 'voting right',
 'sale rose',
 'adp news',
 'month period',
 'eur mn',
 'option right',
 'swung net',
 'contract manufacturing',
 'half compared',
 'usd eur',
 'technology company',
 'ahlstrom corporation',
 'ñnnen tehtaat',
 'rose eur',
 'equipment maker',
 'sale fell',
 'million compared',
 'management company',
 'increase s

In [ ]:
# Create a new dataframe with the top 200 positive, negative, and neutral words as features
new_dff = pd.DataFrame()
for word in top_positive_words_bigram + top_negative_words_bigram + top_neutral_words_bigram:
    new_dff[word] = df['Sentence'].apply(lambda x: 1 if word in x else 0)
new_dff['Sentiment'] = df['Sentiment']

In [ ]:
new_dff

profit fell  outside finland  sector player  eur corresponding  \
0               0                0              0                  0   
1               0                0              0                  0   
2               0                0              0                  0   
3               0                0              0                  0   
4               0                0              0                  0   
...           ...              ...            ...                ...   
5837            0                0              0                  0   
5838            0                0              0                  0   
5839            0                0              0                  0   
5840            0                0              0                  0   
5841            0                0              0                  0   

      based company  chairman board  share eur  earnings share  \
0                 0               0          0               0   
1                 0               0          0               0   
2                 0               0          0               0   
3                 0               0          0               0   
4                 0               0          0               0   
...             ...             ...        ...             ...   
5837              0               0          0               0   
5838              0               0          0               0   
5839              0               0          0               0   
5840              0               0          0               0   
5841              0               0          0               0   

      global research  eur billion  ...  company stock  profit tax  \
0                   0            0  ...              0           0   
1                   0            0  ...              0           0   
2                   0            0  ...              0           0   
3                   0            0  ...              0           0   
4                   0            0  ...              0           0   
...               ...          ...  ...            ...         ...   
5837                0            0  ...              0           0   
5838                0            0  ...              0           0   
5839                0            0  ...              0           0   
5840                0            0  ...              0           0   
5841                0            0  ...              0           0   

      tekla structure  half eur  compared loss  recall model  \
0                   0         0              0             0   
1                   0         0              0             0   
2                   0         0              0             0   
3                   0         0              0             0   
4                   0         0              0             0   
...               ...       ...            ...           ...   
5837                0         0              0             0   
5838                0         0              0             0   
5839                0         0              0             0   
5840                0         0              0             0   
5841                0         0              0             0   

      contract includes  feb finnish  year million  Sentiment  
0                     0            0             0   positive  
1                     0            0             0   negative  
2                     0            0             0   positive  
3                     0            0             0    neutral  
4                     0            0             0    neutral  
...                 ...          ...           ...        ...  
5837                  0            0             0   negative  
5838                  0            0             0    neutral  
5839                  0            0             0    neutral  
5840                  0            0             0    neutral  
5841                  0           

In [ ]:
from sklearn.preprocessing import LabelEncoder
le_encoder = LabelEncoder()
new_dff["Labels"] = le_encoder.fit_transform(new_dff["Sentiment"])
new_dff.head()

profit fell  outside finland  sector player  eur corresponding  \
0            0                0              0                  0   
1            0                0              0                  0   
2            0                0              0                  0   
3            0                0              0                  0   
4            0                0              0                  0   

   based company  chairman board  share eur  earnings share  global research  \
0              0               0          0               0                0   
1              0               0          0               0                0   
2              0               0          0               0                0   
3              0               0          0               0                0   
4              0               0          0               0                0   

   eur billion  ...  profit tax  tekla structure  half eur  compared loss  \
0            0  ...           0                0         0              0   
1            0  ...           0                0         0              0   
2            0  ...           0                0         0              0   
3            0  ...           0                0         0              0   
4            0  ...           0                0         0              0   

   recall model  contract includes  feb finnish  year million  Sentiment  \
0             0                  0            0             0   positive   
1             0                  0            0             0   negative   
2             0                  0            0             0   positive   
3             0                  0            0             0    neutral   
4             0                  0            0             0    neutral   

   Labels  
0       2  
1       0  
2       2  
3       1  
4       1  

[5 rows x 502 columns]

In [ ]:
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(new_dff.drop(['Sentiment','Labels'], axis=1), new_dff['Labels'], test_size=0.2)

# Train a Naive Bayes classifier on the training set
clf = MultinomialNB()
clf.fit(X_train, y_train)

# Test the model on the testing set and print the accuracy score
accuracy = clf.score(X_test, y_test)
print('Accuracy:', accuracy)


Accuracy: 0.586472602739726


In [ ]:
clf = LogisticRegression()
clf.fit(X_train, y_train)

# Test the model on the testing set and print the accuracy score
accuracy = clf.score(X_test, y_test)
print('Accuracy:', accuracy)

Accuracy: 0.5813356164383562


In [ ]:
import xgboost as xgb

In [ ]:
# Train an XGBoost model on the training set
dtrain = xgb.DMatrix(X_train, label=y_train)
dtest = xgb.DMatrix(X_test, label=y_test)

param = {
    'max_depth': 6,
    'eta': 0.3,
    'objective': 'multi:softmax',
    'num_class': 3
}

num_round = 100
model = xgb.train(param, dtrain, num_round)

# Test the model on the testing set and print the accuracy score
preds = model.predict(dtest)
accuracy = sum(preds == y_test) / len(y_test)
print('Accuracy:', accuracy)

Accuracy: 0.5753424657534246


In [ ]:

from sklearn.feature_extraction.text import TfidfVectorizer
# Extract the top 200 unique positive, negative, and neutral words
vectorizer = TfidfVectorizer(max_features=200, stop_words='english',ngram_range=(3, 3))
X = vectorizer.fit_transform(df['Sentence'])
y = df['Sentiment']
features = vectorizer.vocabulary_.keys()
freq = X.sum(axis=0).A1
word_freq = dict(zip(features, freq))
sorted_words = sorted(word_freq.items(), key=lambda x: x[1], reverse=True)
top_positive_words_trigram = [word[0] for word in sorted_words if word[0] not in ['negative', 'neutral'] and word[1] > 0][:200]
top_negative_words_trigram = [word[0] for word in sorted_words if word[0] not in ['positive', 'neutral'] and word[1] > 0][:200]
top_neutral_words_trigram = [word[0] for word in sorted_words if word[0] not in ['positive', 'negative'] and word[1] > 0][:200]

In [ ]:
top_positive_words_trigram

['month period decreased',
 'eur mn net',
 'analysis clear overview',
 'totaled eur mn',
 'profit totalled eur',
 'operating profit totaled',
 'profit totaled eur',
 'issued profit warning',
 'today slipped net',
 'supplier contract manufacturer',
 'net profit rose',
 'share capital voting',
 'scanfil supplier contract',
 'said net profit',
 'eur mn january',
 'quarter eur mn',
 'loss eur million',
 'eur mn second',
 'percent million liter',
 'mln mln euro',
 'totalled eur mn',
 'headquartered helsinki finland',
 'eur mn compared',
 'sale eur million',
 'period increased respectively',
 'operating profit excluding',
 'operating profit fell',
 'operating profit eur',
 'mn compared profit',
 'decreased eur million',
 'eur mn corresponding',
 'actual situation future',
 'operating profit totalled',
 'decreased eur mn',
 'research data service',
 'diluted earnings share',
 'contract manufacturer scanfil',
 'net sale quarter',
 'item totalled eur',
 'maker rautaruukki oyj',
 'loss totalled 

In [ ]:
# Create a new dataframe with the top 200 positive, negative, and neutral words as features
new_dfff = pd.DataFrame()
for word in top_positive_words_trigram + top_negative_words_trigram + top_neutral_words_trigram:
    new_dfff[word] = df['Sentence'].apply(lambda x: 1 if word in x else 0)
new_dfff['Sentiment'] = df['Sentiment']

In [ ]:
from sklearn.preprocessing import LabelEncoder
le_encoder = LabelEncoder()
new_dfff["Labels"] = le_encoder.fit_transform(new_dfff["Sentiment"])
new_dfff.head()

month period decreased  eur mn net  analysis clear overview  \
0                       0           0                        0   
1                       0           0                        0   
2                       0           0                        0   
3                       0           0                        0   
4                       0           0                        0   

   totaled eur mn  profit totalled eur  operating profit totaled  \
0               0                    0                         0   
1               0                    0                         0   
2               0                    0                         0   
3               0                    0                         0   
4               0                    0                         0   

   profit totaled eur  issued profit warning  today slipped net  \
0                   0                      0                  0   
1                   0                      0                  0   
2                   0                      0                  0   
3                   0                      0                  0   
4                   0                      0                  0   

   supplier contract manufacturer  ...  million eur million  \
0                               0  ...                    0   
1                               0  ...                    0   
2                               0  ...                    0   
3                               0  ...                    0   
4                               0  ...                    0   

   profit eur million  today net profit  share eps amounted  mn quarter eur  \
0                   0                 0                   0               0   
1                   0                 0                   0               0   
2                   0                 0                   0               0   
3                   0                 0                   0               0   
4                   0                 0                   0               0   

   euro mln quarter  negative eur mn  sale decreased eur  Sentiment  Labels  
0                 0                0                   0   positive       2  
1                 0                0                   0   negative       0  
2                 0                0                   0   positive       2  
3                 0                0                   0    neutral       1  
4                 0                0                   0    neutral       1  

[5 rows x 202 columns]

In [ ]:
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(new_dfff.drop(['Sentiment','Labels'], axis=1), new_dfff['Labels'], test_size=0.2)

# Train a Naive Bayes classifier on the training set
clf = MultinomialNB()
clf.fit(X_train, y_train)

# Test the model on the testing set and print the accuracy score
accuracy = clf.score(X_test, y_test)
print('Accuracy:', accuracy)


Accuracy: 0.5282534246575342


In [ ]:
clf = LogisticRegression()
clf.fit(X_train, y_train)

# Test the model on the testing set and print the accuracy score
accuracy = clf.score(X_test, y_test)
print('Accuracy:', accuracy)

Accuracy: 0.5376712328767124


In [ ]:
# Train an XGBoost model on the training set
dtrain = xgb.DMatrix(X_train, label=y_train)
dtest = xgb.DMatrix(X_test, label=y_test)

param = {
    'max_depth': 6,
    'eta': 0.3,
    'objective': 'multi:softmax',
    'num_class': 3
}

num_round = 100
model = xgb.train(param, dtrain, num_round)

# Test the model on the testing set and print the accuracy score
preds = model.predict(dtest)
accuracy = sum(preds == y_test) / len(y_test)
print('Accuracy:', accuracy)

Accuracy: 0.5299657534246576


In [ ]:
from sklearn.preprocessing import LabelEncoder
le_encoder = LabelEncoder()
df["Labels"] = le_encoder.fit_transform(df["Sentiment"])
df.head()

Sentence Sentiment  Labels
0  geosolutions technology leverage benefon gps s...  positive       2
1                        esi low bk real possibility  negative       0
2  last quarter componenta net sale doubled eurm ...  positive       2
3  according finnish russian chamber commerce maj...   neutral       1
4  swedish buyout firm sold remaining percent sta...   neutral       1

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train, Y_test = train_test_split(df['Sentence'], df['Labels'], test_size=0.25, random_state=30)
print("Train: ",X_train.shape,Y_train.shape,"Test: ",(X_test.shape,Y_test.shape))

Train:  (4377,) (4377,) Test:  ((1459,), (1459,))


In [ ]:
import sklearn
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
x_train = df[:4377]
x_test = df[4377:]
 
vectorizer = sklearn.feature_extraction.text.TfidfVectorizer(use_idf=True,ngram_range=(1,1))
tfidf_features_train = vectorizer.fit_transform(x_train['Sentence'])
tfidf_features_test = vectorizer.transform(x_test['Sentence'])
print (tfidf_features_train.shape, tfidf_features_test.shape)

(4377, 8024) (1459, 8024)


In [ ]:
train_labels = [1 if Sentiment=='positive' else 2 if Sentiment=='neutral' else 0 for Sentiment in x_train['Sentiment']]
test_labels = [1 if Sentiment=='positive' else 2 if Sentiment=='neutral' else 0 for Sentiment in x_test['Sentiment']]
print (len(train_labels), len(test_labels))

4377 1459


# Logistic Regression Classifier

In [ ]:
#Logistic Regression
#Create features for Unigram
vectorizer = sklearn.feature_extraction.text.TfidfVectorizer(use_idf=True,ngram_range=(1,1))
tfidf_features_train = vectorizer.fit_transform(x_train['Sentence'])
tfidf_features_test = vectorizer.transform(x_test['Sentence'])
print (tfidf_features_train.shape, tfidf_features_test.shape)
 
#train model
clf = sklearn.linear_model.LogisticRegression()
clf.fit(tfidf_features_train, train_labels)
 
#evaluation
predictions = clf.predict(tfidf_features_test)
print(sklearn.metrics.classification_report(test_labels, predictions, target_names=['Negative', 'Positive','Neutral']))
print(sklearn.metrics.confusion_matrix(test_labels, predictions, labels=[0, 1, 2]))

(4377, 8024) (1459, 8024)
              precision    recall  f1-score   support

    Negative       0.51      0.17      0.25       225
    Positive       0.71      0.59      0.64       455
     Neutral       0.69      0.89      0.78       779

    accuracy                           0.69      1459
   macro avg       0.64      0.55      0.56      1459
weighted avg       0.67      0.69      0.65      1459

[[ 38  55 132]
 [  4 267 184]
 [ 32  52 695]]


In [ ]:
#Create features for Bigram
vectorizer = sklearn.feature_extraction.text.TfidfVectorizer(use_idf=True,ngram_range=(2,2))
tfidf_features_train = vectorizer.fit_transform(x_train['Sentence'])
tfidf_features_test = vectorizer.transform(x_test['Sentence'])
print (tfidf_features_train.shape, tfidf_features_test.shape)
 
#train model
clf = sklearn.linear_model.LogisticRegression()
clf.fit(tfidf_features_train, train_labels)
 
#evaluation
predictions = clf.predict(tfidf_features_test)
print(sklearn.metrics.classification_report(test_labels, predictions, target_names=['Negative', 'Positive','Neutral']))
print(sklearn.metrics.confusion_matrix(test_labels, predictions, labels=[0, 1, 2]))

(4377, 31542) (1459, 31542)
              precision    recall  f1-score   support

    Negative       0.30      0.06      0.10       225
    Positive       0.69      0.33      0.45       455
     Neutral       0.60      0.92      0.72       779

    accuracy                           0.60      1459
   macro avg       0.53      0.44      0.42      1459
weighted avg       0.58      0.60      0.54      1459

[[ 13  35 177]
 [  0 151 304]
 [ 31  34 714]]


In [ ]:
#Create features for Trigram
vectorizer = sklearn.feature_extraction.text.TfidfVectorizer(use_idf=True,ngram_range=(3,3))
tfidf_features_train = vectorizer.fit_transform(x_train['Sentence'])
tfidf_features_test = vectorizer.transform(x_test['Sentence'])
print (tfidf_features_train.shape, tfidf_features_test.shape)
 
#train model
clf = sklearn.linear_model.LogisticRegression()
clf.fit(tfidf_features_train, train_labels)
 
#evaluation
predictions = clf.predict(tfidf_features_test)
print(sklearn.metrics.classification_report(test_labels, predictions, target_names=['Negative', 'Positive','Neutral']))
print(sklearn.metrics.confusion_matrix(test_labels, predictions, labels=[0, 1, 2]))

(4377, 33996) (1459, 33996)
              precision    recall  f1-score   support

    Negative       0.26      0.04      0.07       225
    Positive       0.75      0.19      0.30       455
     Neutral       0.57      0.95      0.71       779

    accuracy                           0.57      1459
   macro avg       0.53      0.39      0.36      1459
weighted avg       0.58      0.57      0.48      1459

[[  9  16 200]
 [  0  86 369]
 [ 25  12 742]]


# MultiNomial Naive Bayes

In [ ]:
#Create features for Unigram
vectorizer = sklearn.feature_extraction.text.TfidfVectorizer(use_idf=True,ngram_range=(1,1))
tfidf_features_train = vectorizer.fit_transform(x_train['Sentence'])
tfidf_features_test = vectorizer.transform(x_test['Sentence'])
print (tfidf_features_train.shape, tfidf_features_test.shape)
 
clf = MultinomialNB()
clf.fit(tfidf_features_train, train_labels)
 
#evaluation
predictions = clf.predict(tfidf_features_test)
print(sklearn.metrics.classification_report(test_labels, predictions, target_names=['Negative', 'Positive','Neutral']))
print(sklearn.metrics.confusion_matrix(test_labels, predictions, labels=[0, 1, 2]))

(4377, 8024) (1459, 8024)
              precision    recall  f1-score   support

    Negative       0.80      0.04      0.07       225
    Positive       0.68      0.42      0.52       455
     Neutral       0.65      0.97      0.77       779

    accuracy                           0.65      1459
   macro avg       0.71      0.47      0.45      1459
weighted avg       0.68      0.65      0.59      1459

[[  8  66 151]
 [  1 191 263]
 [  1  24 754]]


In [ ]:
#Create features for Bigram
vectorizer = sklearn.feature_extraction.text.TfidfVectorizer(use_idf=True,ngram_range=(2,2))
tfidf_features_train = vectorizer.fit_transform(x_train['Sentence'])
tfidf_features_test = vectorizer.transform(x_test['Sentence'])
print (tfidf_features_train.shape, tfidf_features_test.shape)
 
clf = MultinomialNB()
clf.fit(tfidf_features_train, train_labels)
 
#evaluation
predictions = clf.predict(tfidf_features_test)
print(sklearn.metrics.classification_report(test_labels, predictions, target_names=['Negative', 'Positive','Neutral']))
print(sklearn.metrics.confusion_matrix(test_labels, predictions, labels=[0, 1, 2]))

(4377, 31542) (1459, 31542)
              precision    recall  f1-score   support

    Negative       0.22      0.02      0.03       225
    Positive       0.70      0.32      0.44       455
     Neutral       0.60      0.94      0.73       779

    accuracy                           0.61      1459
   macro avg       0.51      0.43      0.40      1459
weighted avg       0.57      0.61      0.53      1459

[[  4  33 188]
 [  0 146 309]
 [ 14  29 736]]


In [ ]:
#Create features for Trigram
vectorizer = sklearn.feature_extraction.text.TfidfVectorizer(use_idf=True,ngram_range=(3,3))
tfidf_features_train = vectorizer.fit_transform(x_train['Sentence'])
tfidf_features_test = vectorizer.transform(x_test['Sentence'])
print (tfidf_features_train.shape, tfidf_features_test.shape)
 
clf = MultinomialNB()
clf.fit(tfidf_features_train, train_labels)
 
#evaluation
predictions = clf.predict(tfidf_features_test)
print(sklearn.metrics.classification_report(test_labels, predictions, target_names=['Negative', 'Positive','Neutral']))
print(sklearn.metrics.confusion_matrix(test_labels, predictions, labels=[0, 1, 2]))

(4377, 33996) (1459, 33996)
              precision    recall  f1-score   support

    Negative       0.12      0.01      0.02       225
    Positive       0.72      0.20      0.31       455
     Neutral       0.56      0.95      0.71       779

    accuracy                           0.57      1459
   macro avg       0.47      0.39      0.34      1459
weighted avg       0.54      0.57      0.48      1459

[[  2  14 209]
 [  0  89 366]
 [ 15  21 743]]


# LSVM

In [ ]:
#Create features for Unigram
vectorizer = sklearn.feature_extraction.text.TfidfVectorizer(use_idf=True,ngram_range=(1,1))
tfidf_features_train = vectorizer.fit_transform(x_train['Sentence'])
tfidf_features_test = vectorizer.transform(x_test['Sentence'])
print (tfidf_features_train.shape, tfidf_features_test.shape)
 
clf = sklearn.svm.LinearSVC()
clf.fit(tfidf_features_train, train_labels)
 
#evaluation
predictions = clf.predict(tfidf_features_test)
print(sklearn.metrics.classification_report(test_labels, predictions, target_names=['Negative', 'Positive','Neutral']))
print(sklearn.metrics.confusion_matrix(test_labels, predictions, labels=[0, 1, 2]))

(4377, 8024) (1459, 8024)
              precision    recall  f1-score   support

    Negative       0.36      0.26      0.30       225
    Positive       0.72      0.69      0.70       455
     Neutral       0.71      0.78      0.74       779

    accuracy                           0.67      1459
   macro avg       0.59      0.58      0.58      1459
weighted avg       0.66      0.67      0.66      1459

[[ 58  48 119]
 [ 10 315 130]
 [ 95  76 608]]


In [ ]:
#Create features for Bigram
vectorizer = sklearn.feature_extraction.text.TfidfVectorizer(use_idf=True,ngram_range=(2,2))
tfidf_features_train = vectorizer.fit_transform(x_train['Sentence'])
tfidf_features_test = vectorizer.transform(x_test['Sentence'])
print (tfidf_features_train.shape, tfidf_features_test.shape)
 
clf = sklearn.svm.LinearSVC()
clf.fit(tfidf_features_train, train_labels)
 
#evaluation
predictions = clf.predict(tfidf_features_test)
print(sklearn.metrics.classification_report(test_labels, predictions, target_names=['Negative', 'Positive','Neutral']))
print(sklearn.metrics.confusion_matrix(test_labels, predictions, labels=[0, 1, 2]))

(4377, 31542) (1459, 31542)
              precision    recall  f1-score   support

    Negative       0.18      0.11      0.14       225
    Positive       0.64      0.47      0.54       455
     Neutral       0.60      0.77      0.68       779

    accuracy                           0.57      1459
   macro avg       0.48      0.45      0.45      1459
weighted avg       0.55      0.57      0.55      1459

[[ 25  43 157]
 [  5 215 235]
 [106  76 597]]


In [ ]:
#Create features for Trigram
vectorizer = sklearn.feature_extraction.text.TfidfVectorizer(use_idf=True,ngram_range=(3,3))
tfidf_features_train = vectorizer.fit_transform(x_train['Sentence'])
tfidf_features_test = vectorizer.transform(x_test['Sentence'])
print (tfidf_features_train.shape, tfidf_features_test.shape)
 
clf = sklearn.svm.LinearSVC()
clf.fit(tfidf_features_train, train_labels)
 
#evaluation
predictions = clf.predict(tfidf_features_test)
print(sklearn.metrics.classification_report(test_labels, predictions, target_names=['Negative', 'Positive','Neutral']))
print(sklearn.metrics.confusion_matrix(test_labels, predictions, labels=[0, 1, 2]))

(4377, 33996) (1459, 33996)
              precision    recall  f1-score   support

    Negative       0.15      0.08      0.11       225
    Positive       0.69      0.27      0.39       455
     Neutral       0.56      0.83      0.67       779

    accuracy                           0.54      1459
   macro avg       0.47      0.40      0.39      1459
weighted avg       0.54      0.54      0.50      1459

[[ 19  26 180]
 [  2 124 329]
 [102  31 646]]
